import UIKit

enum InvoicePDFGenerator {
    static func generate(record: JobRecord) -> Data {
        let pageRect = CGRect(x: 0, y: 0, width: 595, height: 842) // A4
        let renderer = UIGraphicsPDFRenderer(bounds: pageRect)

        return renderer.pdfData { ctx in
            ctx.beginPage()
            let g = ctx.cgContext

            // Header background
            g.setFillColor(UIColor.systemOrange.cgColor)
            g.fill(CGRect(x: 0, y: 0, width: 595, height: 80))

            // Company / App name
            draw("TradecraftAI", rect: CGRect(x: 30, y: 20, width: 300, height: 40),
                 font: .boldSystemFont(ofSize: 26), color: .white)

            // Invoice label
            draw("INVOICE", rect: CGRect(x: 400, y: 28, width: 165, height: 30),
                 font: .boldSystemFont(ofSize: 18), color: .white, alignment: .right)

            var y: CGFloat = 100

            // Date & Trade
            let dateStr = record.createdAt.formatted(date: .long, time: .shortened)
            drawPair("Date:", dateStr, y: y, pageWidth: 595)
            y += 24
            drawPair("Trade:", record.trade, y: y, pageWidth: 595)
            y += 24
            drawPair("Type:", record.type.rawValue, y: y, pageWidth: 595)
            y += 36

            // Divider
            g.setStrokeColor(UIColor.separator.cgColor)
            g.setLineWidth(0.5)
            g.move(to: CGPoint(x: 30, y: y))
            g.addLine(to: CGPoint(x: 565, y: y))
            g.strokePath()
            y += 16

            // Job description
            if !record.inputText.isEmpty {
                draw("Job Description", rect: CGRect(x: 30, y: y, width: 500, height: 22),
                     font: .boldSystemFont(ofSize: 13), color: .darkGray)
                y += 26
                y = drawWrapped(record.inputText, x: 30, y: y, width: 535,
                                font: .systemFont(ofSize: 11), color: .darkGray, pageRect: pageRect)
                y += 20
            }

            // Result
            draw("Estimate / Result", rect: CGRect(x: 30, y: y, width: 500, height: 22),
                 font: .boldSystemFont(ofSize: 13), color: .darkGray)
            y += 26
            drawWrapped(record.resultText, x: 30, y: y, width: 535,
                        font: .systemFont(ofSize: 11), color: .black, pageRect: pageRect)

            // Footer
            let footerY: CGFloat = pageRect.height - 36
            draw("Generated by TradecraftAI · \(dateStr)",
                 rect: CGRect(x: 30, y: footerY, width: 535, height: 20),
                 font: .systemFont(ofSize: 9), color: .lightGray, alignment: .center)
        }
    }

    // MARK: - Helpers
    @discardableResult
    private static func draw(_ text: String, rect: CGRect, font: UIFont, color: UIColor, alignment: NSTextAlignment = .left) -> CGFloat {
        let para = NSMutableParagraphStyle()
        para.alignment = alignment
        let attrs: [NSAttributedString.Key: Any] = [
            .font: font, .foregroundColor: color, .paragraphStyle: para
        ]
        text.draw(in: rect, withAttributes: attrs)
        return rect.maxY
    }

    private static func drawPair(_ label: String, _ value: String, y: CGFloat, pageWidth: CGFloat) {
        draw(label, rect: CGRect(x: 30, y: y, width: 100, height: 20),
             font: .boldSystemFont(ofSize: 11), color: .darkGray)
        draw(value, rect: CGRect(x: 135, y: y, width: pageWidth - 165, height: 20),
             font: .systemFont(ofSize: 11), color: .black)
    }

    @discardableResult
    private static func drawWrapped(_ text: String, x: CGFloat, y: CGFloat, width: CGFloat,
                                    font: UIFont, color: UIColor, pageRect: CGRect) -> CGFloat {
        let attrs: [NSAttributedString.Key: Any] = [.font: font, .foregroundColor: color]
        let maxH = pageRect.height - y - 50
        let rect  = CGRect(x: x, y: y, width: width, height: maxH)
        text.draw(in: rect, withAttributes: attrs)
        let boundingH = (text as NSString).boundingRect(
            with: CGSize(width: width, height: maxH),
            options: [.usesLineFragmentOrigin],
            attributes: attrs, context: nil).height
        return y + boundingH
    }
}
